@startuml                                                 
title TCP/IP Packet Processing                                               
                                               
start                                                    
                                                       
while (Incoming pakcet ?) 

if (Is destination mac address for current interface ?) then (yes)
    if (Is type IPv4 ?) then (yes) 
        partition "Process IPv4" {                                   
            if (Is version IPv4 ?) then (yes)
                if (Is the header length greater than 20 byte ?) then (yes)
                    if (Is TTL 0 ?) then (yes)
                        :Send ICMP error;
                    else (no)
                        :Validate checksum;
                        :Check fragmentation and reassemble;
                        if (Is protocol TCP ?) then (yes)
                            partition "Process TCP" {
                            }
                        elseif (Is protocol ICMPv4 ?) then (yes)
                            partition "Process ICMPv4" {
                                :Validate checksum;
                                if (Is type echo request ?) then (yes)
                                    :Send echo reply;
                                else (no)
                                    #AAAAAA:Drop the packet;                                  
                                endif
                            }
                        else (no)
                            #AAAAAA:Drop the packet;                                  
                        endif
                    endif
                else (no)
                    #AAAAAA:Drop the packet;                                  
                endif
            else (no)
                #AAAAAA:Drop the packet;                                  
            endif
        }                                             
    elseif (Is type ARP ?) then (yes)
        partition "Process ARP" {
            if (Is hardware type ethernet ?) then (yes)
                if (Is protocol type IPv4 ?) then (yes)
                    if (Is target IP address for current interface ?) then (yes)
                        :Insert ARP translation table;
                        if (Is opcode REQUEST ?) then (yes)
                            :Create ARP reply;
                            :Send ARP reply;
                        endif
                    else (no)
                        #AAAAAA:Drop the packet;                                  
                    endif
                else (no)
                    #AAAAAA:Drop the packet;                                  
                endif
            else (no)
                #AAAAAA:Drop the packet;                                  
            endif
        }
    else (no)
        #AAAAAA:Drop the packet;                                  
    endif
else (no)                                                  
    #AAAAAA:Drop the packet;                                  
endif                                                 

endwhile
                                       
stop 
@enduml